"""
Seed list of companies to poll for the daily discovery pipeline, keyed by their
public ATS job-board API. Slugs are verified against the live APIs (not guessed) —
see boards-api.greenhouse.io / api.lever.co / api.ashbyhq.com.

h1b_known marks companies generally recognized as established H-1B sponsors (used
as a light prioritization signal on top of the per-posting sponsorship language
the AI already extracts from each JD).
"""

SEED_COMPANIES = [
    # Greenhouse — verified via boards-api.greenhouse.io/v1/boards/{slug}/jobs
    {"name": "Stripe", "ats": "greenhouse", "slug": "stripe", "h1b_known": True},
    {"name": "Airbnb", "ats": "greenhouse", "slug": "airbnb", "h1b_known": True},
    {"name": "Robinhood", "ats": "greenhouse", "slug": "robinhood", "h1b_known": True},
    {"name": "Asana", "ats": "greenhouse", "slug": "asana", "h1b_known": True},
    {"name": "Pinterest", "ats": "greenhouse", "slug": "pinterest", "h1b_known": True},
    {"name": "Affirm", "ats": "greenhouse", "slug": "affirm", "h1b_known": True},
    {"name": "Coinbase", "ats": "greenhouse", "slug": "coinbase", "h1b_known": True},
    {"name": "Discord", "ats": "greenhouse", "slug": "discord", "h1b_known": True},
    {"name": "Figma", "ats": "greenhouse", "slug": "figma", "h1b_known": True},
    {"name": "Datadog", "ats": "greenhouse", "slug": "datadog", "h1b_known": True},
    {"name": "GitLab", "ats": "greenhouse", "slug": "gitlab", "h1b_known": True},
    {"name": "Cloudflare", "ats": "greenhouse", "slug": "cloudflare", "h1b_known": True},
    {"name": "Twilio", "ats": "greenhouse", "slug": "twilio", "h1b_known": True},
    {"name": "Reddit", "ats": "greenhouse", "slug": "reddit", "h1b_known": True},
    {"name": "Brex", "ats": "greenhouse", "slug": "brex", "h1b_known": True},
    {"name": "Gusto", "ats": "greenhouse", "slug": "gusto", "h1b_known": True},
    {"name": "Instacart", "ats": "greenhouse", "slug": "instacart", "h1b_known": True},
    {"name": "Lyft", "ats": "greenhouse", "slug": "lyft", "h1b_known": True},
    {"name": "Roblox", "ats": "greenhouse", "slug": "roblox", "h1b_known": True},
    {"name": "Dropbox", "ats": "greenhouse", "slug": "dropbox", "h1b_known": True},
    {"name": "Okta", "ats": "greenhouse", "slug": "okta", "h1b_known": True},
    {"name": "Samsara", "ats": "greenhouse", "slug": "samsara", "h1b_known": True},
    {"name": "Zscaler", "ats": "greenhouse", "slug": "zscaler", "h1b_known": True},
    {"name": "MongoDB", "ats": "greenhouse", "slug": "mongodb", "h1b_known": True},
    {"name": "Elastic", "ats": "greenhouse", "slug": "elastic", "h1b_known": True},
    {"name": "Anthropic", "ats": "greenhouse", "slug": "anthropic", "h1b_known": True},
    {"name": "Scale AI", "ats": "greenhouse", "slug": "scaleai", "h1b_known": True},
    {"name": "Airtable", "ats": "greenhouse", "slug": "airtable", "h1b_known": True},
    {"name": "Netlify", "ats": "greenhouse", "slug": "netlify", "h1b_known": True},
    {"name": "Webflow", "ats": "greenhouse", "slug": "webflow", "h1b_known": True},
    {"name": "Carta", "ats": "greenhouse", "slug": "carta", "h1b_known": True},
    {"name": "Flexport", "ats": "greenhouse", "slug": "flexport", "h1b_known": True},
    {"name": "Nextdoor", "ats": "greenhouse", "slug": "nextdoor", "h1b_known": True},
    {"name": "Faire", "ats": "greenhouse", "slug": "faire", "h1b_known": True},
    {"name": "Betterment", "ats": "greenhouse", "slug": "betterment", "h1b_known": True},
    {"name": "Fastly", "ats": "greenhouse", "slug": "fastly", "h1b_known": True},
    {"name": "New Relic", "ats": "greenhouse", "slug": "newrelic", "h1b_known": True},
    {"name": "PagerDuty", "ats": "greenhouse", "slug": "pagerduty", "h1b_known": True},
    {"name": "Intercom", "ats": "greenhouse", "slug": "intercom", "h1b_known": True},
    {"name": "Calendly", "ats": "greenhouse", "slug": "calendly", "h1b_known": True},
    {"name": "PlanetScale", "ats": "greenhouse", "slug": "planetscale", "h1b_known": False},
    {"name": "Block", "ats": "greenhouse", "slug": "block", "h1b_known": True},
    {"name": "Adyen", "ats": "greenhouse", "slug": "adyen", "h1b_known": True},
    {"name": "Wise", "ats": "greenhouse", "slug": "wise", "h1b_known": True},
    {"name": "Monzo", "ats": "greenhouse", "slug": "monzo", "h1b_known": False},
    {"name": "Current", "ats": "greenhouse", "slug": "current", "h1b_known": False},
    {"name": "SoFi", "ats": "greenhouse", "slug": "sofi", "h1b_known": True},
    {"name": "Upstart", "ats": "greenhouse", "slug": "upstart", "h1b_known": True},
    {"name": "Midi Health", "ats": "greenhouse", "slug": "midihealth", "h1b_known": False},
    {"name": "Coursera", "ats": "greenhouse", "slug": "coursera", "h1b_known": True},
    {"name": "Duolingo", "ats": "greenhouse", "slug": "duolingo", "h1b_known": True},
    {"name": "Peloton", "ats": "greenhouse", "slug": "peloton", "h1b_known": True},
    {"name": "Calm", "ats": "greenhouse", "slug": "calm", "h1b_known": False},
    {"name": "Lattice", "ats": "greenhouse", "slug": "lattice", "h1b_known": False},
    {"name": "Culture Amp", "ats": "greenhouse", "slug": "cultureamp", "h1b_known": False},
    {"name": "Typeform", "ats": "greenhouse", "slug": "typeform", "h1b_known": False},
    {"name": "Smartsheet", "ats": "greenhouse", "slug": "smartsheet", "h1b_known": True},
    {"name": "Wrike", "ats": "greenhouse", "slug": "wrike", "h1b_known": False},
    {"name": "Twitch", "ats": "greenhouse", "slug": "twitch", "h1b_known": True},
    {"name": "Glossier", "ats": "greenhouse", "slug": "glossier", "h1b_known": False},
    {"name": "Stitch Fix", "ats": "greenhouse", "slug": "stitchfix", "h1b_known": True},
    {"name": "Gemini", "ats": "greenhouse", "slug": "gemini", "h1b_known": False},
    {"name": "Consensys", "ats": "greenhouse", "slug": "consensys", "h1b_known": False},
    {"name": "N26", "ats": "greenhouse", "slug": "n26", "h1b_known": False},
    {"name": "Toast", "ats": "greenhouse", "slug": "toast", "h1b_known": True},

    # Amazon — custom search API (amazon.jobs/en/search.json), not a per-slug ATS board
    {"name": "Amazon", "ats": "amazon", "slug": "amazon", "h1b_known": True},

    # Lever — verified via api.lever.co/v0/postings/{slug}?mode=json
    {"name": "Palantir", "ats": "lever", "slug": "palantir", "h1b_known": True},
    {"name": "Wealthfront", "ats": "lever", "slug": "wealthfront", "h1b_known": True},
    {"name": "Tala", "ats": "lever", "slug": "tala", "h1b_known": False},
    {"name": "Greenlight", "ats": "lever", "slug": "greenlight", "h1b_known": False},
    {"name": "Outreach", "ats": "lever", "slug": "outreach", "h1b_known": True},

    # Ashby — verified via api.ashbyhq.com/posting-api/job-board/{slug}
    {"name": "Notion", "ats": "ashby", "slug": "notion", "h1b_known": True},
    {"name": "Perplexity", "ats": "ashby", "slug": "perplexity", "h1b_known": False},
    {"name": "Ramp", "ats": "ashby", "slug": "ramp", "h1b_known": True},
    {"name": "Linear", "ats": "ashby", "slug": "linear", "h1b_known": False},
    {"name": "Replit", "ats": "ashby", "slug": "replit", "h1b_known": False},
    {"name": "Vanta", "ats": "ashby", "slug": "vanta", "h1b_known": False},
    {"name": "Hex", "ats": "ashby", "slug": "hex", "h1b_known": False},
    {"name": "Cohere", "ats": "ashby", "slug": "cohere", "h1b_known": True},
    {"name": "Pinecone", "ats": "ashby", "slug": "pinecone", "h1b_known": False},
    {"name": "LangChain", "ats": "ashby", "slug": "langchain", "h1b_known": False},
    {"name": "Sierra", "ats": "ashby", "slug": "sierra", "h1b_known": False},
    {"name": "Harvey", "ats": "ashby", "slug": "harvey", "h1b_known": False},
    {"name": "Supabase", "ats": "ashby", "slug": "supabase", "h1b_known": False},
    {"name": "Modal", "ats": "ashby", "slug": "modal", "h1b_known": False},
    {"name": "Fireworks AI", "ats": "ashby", "slug": "fireworks", "h1b_known": False},
    {"name": "Braintrust", "ats": "ashby", "slug": "braintrust", "h1b_known": False},
    {"name": "Cursor", "ats": "ashby", "slug": "cursor", "h1b_known": False},
    {"name": "Runway", "ats": "ashby", "slug": "runway", "h1b_known": True},
    {"name": "Suno", "ats": "ashby", "slug": "suno", "h1b_known": False},
    {"name": "ElevenLabs", "ats": "ashby", "slug": "elevenlabs", "h1b_known": False},
    {"name": "Character.AI", "ats": "ashby", "slug": "character", "h1b_known": True},
    {"name": "Writer", "ats": "ashby", "slug": "writer", "h1b_known": False},
    {"name": "Baseten", "ats": "ashby", "slug": "baseten", "h1b_known": False},
    {"name": "OpenAI", "ats": "ashby", "slug": "openai", "h1b_known": True},
    {"name": "Chalk", "ats": "ashby", "slug": "chalk", "h1b_known": False},
    {"name": "Beacon AI", "ats": "ashby", "slug": "beaconai", "h1b_known": False},
    {"name": "OpenSea", "ats": "ashby", "slug": "opensea", "h1b_known": False},
    {"name": "Magic Eden", "ats": "ashby", "slug": "magiceden", "h1b_known": False},
    {"name": "Dapper Labs", "ats": "ashby", "slug": "dapper", "h1b_known": False},
    {"name": "Uniswap Labs", "ats": "ashby", "slug": "uniswap", "h1b_known": False},
    {"name": "Alchemy", "ats": "ashby", "slug": "alchemy", "h1b_known": False},
    {"name": "Dune", "ats": "ashby", "slug": "dune", "h1b_known": False},
    {"name": "Phantom", "ats": "ashby", "slug": "phantom", "h1b_known": False},
    {"name": "Blockdaemon", "ats": "ashby", "slug": "blockdaemon", "h1b_known": False},
    {"name": "Paradigm", "ats": "ashby", "slug": "paradigm", "h1b_known": False},
]
