"""
The 30-day interview-practice plan: one timed React/JS build, one LeetCode set and one frontend
system-design drill per day, ordered from fundamentals to full mock interviews.

Every item carries "say" prompts: the month's goal is to explain the approach while writing it,
so each check-in asks whether that actually happened.
"""
from __future__ import annotations

PLAN_DAYS = 30

TRACKS = {
    "react": {
        "label": "React / JS (timed)",
        "share": 0.50,
        "bar": "Working build within 60 min",
        "goal": "Build a working interactive UI in 45–60 min and explain state, edge cases and improvements.",
    },
    "leetcode": {
        "label": "LeetCode / DSA",
        "share": 0.35,
        "bar": "Solved without hints",
        "goal": "Common Easy problems reliably correct; typical Medium problems explained and written.",
    },
    "system_design": {
        "label": "Frontend System Design",
        "share": 0.15,
        "bar": "Covered components, data flow, requests, performance and errors",
        "goal": "Design a feature's components, data flow, requests, performance and error handling clearly.",
    },
}

WEEK_THEMES = {
    1: "Foundations — state, events, arrays & hashing",
    2: "Async & data — fetching, stacks, binary search, linked lists",
    3: "Complex UI — trees & graphs, real-time design",
    4: "Interview mode — DP, heaps, backtracking, full designs",
    5: "Mock interviews",
}


def _day(n: int, react: tuple, leetcode: tuple, sd: tuple) -> dict:
    r_title, r_brief, r_say = react
    lc_title, problems, lc_say = leetcode
    sd_title, sd_brief, sd_say = sd
    return {
        "day": n,
        "week": min(5, (n - 1) // 7 + 1) if n <= 28 else 5,
        "react": {"key": f"d{n:02d}-react", "title": r_title, "brief": r_brief, "say": r_say},
        "leetcode": {
            "key": f"d{n:02d}-leetcode",
            "title": lc_title,
            "say": lc_say,
            "problems": [
                {
                    "key": f"d{n:02d}-lc-{slug}",
                    "number": num,
                    "name": name,
                    "difficulty": diff,
                    "url": f"https://leetcode.com/problems/{slug}/",
                }
                for num, name, slug, diff in problems
            ],
        },
        "system_design": {"key": f"d{n:02d}-sd", "title": sd_title, "brief": sd_brief, "say": sd_say},
    }


PLAN: list[dict] = [
    # ── Week 1 · Foundations ─────────────────────────────────────────────────
    _day(1,
         ("Todo list", "Add, toggle, edit on double-click, delete; filter All / Active / Done; show items left.",
          "Your state shape and why; stable keys; controlled input; empty or whitespace-only input; what you'd add next."),
         ("Hashing basics", [(1, "Two Sum", "two-sum", "easy"), (217, "Contains Duplicate", "contains-duplicate", "easy")],
          "Brute force first, then the one-pass hash map; time and space; duplicates and the no-answer case."),
         ("Warm-up: like button", "Run the five-part checklist on a like button with a count.",
          "Components and props; where liked/count state lives; the request; optimistic update and rollback; rapid double clicks.")),
    _day(2,
         ("Accessible tabs", "Tabs with keyboard arrows, Home/End, correct roles, and support for controlled or uncontrolled use.",
          "Controlled vs uncontrolled; roving tabindex; ARIA roles; what happens when tabs change dynamically."),
         ("Anagrams", [(242, "Valid Anagram", "valid-anagram", "easy"), (49, "Group Anagrams", "group-anagrams", "medium")],
          "Counting vs sorting as the key; why the grouping key works; complexity of each option."),
         ("Autocomplete", "Search box that suggests results while you type.",
          "Input, list and item components; debounce; request cancelling and stale results; caching; keyboard navigation; empty and error states.")),
    _day(3,
         ("Star rating", "5 stars with hover preview, click to set, clear, keyboard support and a read-only mode.",
          "Hover vs committed value; half-star extension; accessibility (radio group); props API design."),
         ("Frequency counting", [(347, "Top K Frequent Elements", "top-k-frequent-elements", "medium")],
          "Count first, then heap vs bucket sort; why bucket sort is O(n); ties and k larger than distinct values."),
         ("Image carousel / gallery", "Carousel with thumbnails, autoplay and swipe.",
          "Component split; index state and looping; preloading neighbours; lazy loading; reduced motion; broken images.")),
    _day(4,
         ("Modal dialog", "Portal-rendered modal: close on Esc and backdrop, trap focus, restore focus, lock page scroll.",
          "Why a portal; focus trap and restore; stacking several modals; scroll lock side effects; ARIA dialog attributes."),
         ("Two pointers", [(125, "Valid Palindrome", "valid-palindrome", "easy"), (167, "Two Sum II", "two-sum-ii-input-array-is-sorted", "medium")],
          "Why two pointers work on sorted or symmetric input; skipping non-alphanumerics; off-by-one on the pointers."),
         ("Toast & modal system", "App-wide notifications plus confirm dialogs any page can trigger.",
          "Global API (context or event bus); queue and stacking limits; auto-dismiss timers; focus and screen readers; errors from the triggering action.")),
    _day(5,
         ("JS: debounce & throttle", "Implement debounce and throttle with leading/trailing options and cancel().",
          "The difference in one sentence; closures and timers; `this` and arguments; when to pick each in a UI."),
         ("3Sum", [(15, "3Sum", "3sum", "medium")],
          "Sort + two pointers; skipping duplicates at each level; why it's O(n²); early exits."),
         ("Data table", "Table with server-side sorting, filtering and pagination.",
          "Where sort/filter/page state lives (URL?); request shape; cursor vs offset paging; loading skeletons; empty results; slow or failed requests.")),
    _day(6,
         ("Stopwatch & countdown", "Start, pause, resume, reset and laps; countdown variant that fires at zero.",
          "Interval cleanup in effects; why counting ticks drifts and timestamps don't; tab-in-background behaviour."),
         ("Sliding window", [(121, "Best Time to Buy and Sell Stock", "best-time-to-buy-and-sell-stock", "easy"),
                             (3, "Longest Substring Without Repeating Characters", "longest-substring-without-repeating-characters", "medium")],
          "Track the best so far; when the window grows and shrinks; the last-seen index trick; empty input."),
         ("Embeddable poll widget", "A poll that third-party sites drop into their pages.",
          "Script vs iframe embedding; style isolation; talking to your API; rate limiting and duplicate votes; failures on someone else's page.")),
    _day(7,
         ("Nested checkboxes", "Tree of checkboxes where parents reflect children (checked / unchecked / indeterminate).",
          "Tree state shape; propagating up and down; deriving indeterminate instead of storing it; large trees."),
         ("Review + prefix products", [(238, "Product of Array Except Self", "product-of-array-except-self", "medium")],
          "Prefix and suffix products without division; O(1) extra space; zeros in the input. Then redo one missed problem from this week."),
         ("Review: autocomplete in 10 minutes", "Redo Day 2's design from scratch, timed, out loud.",
          "Hit all five parts without notes; notice which part you skipped and why.")),

    # ── Week 2 · Async & data ────────────────────────────────────────────────
    _day(8,
         ("Debounced search", "Search a public API (or a mocked fetch) as you type; loading, empty and error states.",
          "Debounce placement; AbortController or latest-request-wins for race conditions; retry; caching previous queries."),
         ("Stacks", [(20, "Valid Parentheses", "valid-parentheses", "easy"), (155, "Min Stack", "min-stack", "medium")],
          "Why a stack; matching pairs; keeping the minimum alongside each push; empty-stack edge cases."),
         ("News feed", "Infinite-scrolling feed of posts with images.",
          "Cursor pagination; normalizing posts in a cache; new-posts-available banner; image lazy loading; scroll restoration; failed page loads.")),
    _day(9,
         ("JS: Promise utilities", "Implement Promise.all, Promise.race and retry(fn, attempts, backoff).",
          "Result ordering in all(); rejecting fast; exponential backoff with jitter; what you'd test."),
         ("Monotonic stack", [(739, "Daily Temperatures", "daily-temperatures", "medium")],
          "Why the stack stays decreasing; storing indices not values; each element pushed and popped once, so O(n)."),
         ("Nested comments", "Threaded comments with replies, collapse and load-more.",
          "Recursive components; flat vs nested data from the API; pagination inside threads; optimistic posting; deleted parents.")),
    _day(10,
         ("Sortable data table", "Sort by any column (asc/desc), paginate, choose page size.",
          "Derived vs stored sorted data; stable sort; resetting the page when sorting; memoization; very large data."),
         ("Binary search", [(704, "Binary Search", "binary-search", "easy"), (33, "Search in Rotated Sorted Array", "search-in-rotated-sorted-array", "medium")],
          "Loop invariant and boundaries; which half is sorted; avoiding overflow on mid; duplicates."),
         ("Form wizard", "Multi-step signup with validation and a saved draft.",
          "Step components vs one form state; per-step and cross-step validation; saving drafts; back-button behaviour; submit failures.")),
    _day(11,
         ("Infinite scroll list", "Load more with IntersectionObserver; loading, end-of-list and retry states.",
          "Observer setup and cleanup; preventing double fetches; keeping scroll position; accessibility of auto-loading."),
         ("Binary search on answers", [(153, "Find Minimum in Rotated Sorted Array", "find-minimum-in-rotated-sorted-array", "medium")],
          "Compare mid with the right end; why that finds the pivot; the already-sorted case."),
         ("File upload", "Upload large files with progress, pause/cancel and retry.",
          "Chunked or resumable uploads; progress events; concurrency limits; validation before upload; network drops mid-upload.")),
    _day(12,
         ("Autocomplete with keyboard", "Suggestion list with Up/Down/Enter/Esc, highlighted match, mouse and keyboard in sync.",
          "Active index state; aria-activedescendant; closing on blur without losing clicks; highlighting safely (no innerHTML)."),
         ("Linked lists", [(206, "Reverse Linked List", "reverse-linked-list", "easy"), (21, "Merge Two Sorted Lists", "merge-two-sorted-lists", "easy")],
          "Pointer reassignment order; the dummy-head trick; iterative vs recursive and their stack cost."),
         ("Search results page", "Results with filters, sort and pagination that survive refresh and sharing.",
          "URL as the source of truth; debouncing filter changes; SSR or SEO needs; empty and zero-result states; slow queries.")),
    _day(13,
         ("JS: deepClone & deepEqual", "Handle nested objects, arrays, Dates, Maps/Sets and circular references.",
          "Recursion with a WeakMap for cycles; what you deliberately don't support; comparing NaN and -0."),
         ("Fast & slow pointers", [(141, "Linked List Cycle", "linked-list-cycle", "easy"),
                                   (19, "Remove Nth Node From End of List", "remove-nth-node-from-end-of-list", "medium")],
          "Why Floyd's pointers meet; keeping a gap of n; removing the head node."),
         ("E-commerce product page", "Product page with images, variants, reviews and add-to-cart.",
          "Variant state and URL; image optimization for LCP; cart state across tabs; inventory changing under you; failed add-to-cart.")),
    _day(14,
         ("Signup form with validation", "Sync and async validation (username taken), touched/dirty state, submit states.",
          "When to validate (blur vs change vs submit); debounced async checks; disabling vs explaining; server errors mapped to fields."),
         ("Review + LRU cache", [(146, "LRU Cache", "lru-cache", "medium")],
          "Hash map + doubly linked list; O(1) get/put; where you'd use an LRU in a frontend. Then redo one missed problem from this week."),
         ("Review: news feed in 10 minutes", "Redo Day 8's design from scratch, timed, out loud.",
          "All five parts; this time lead with the data model and pagination.")),

    # ── Week 3 · Complex UI ──────────────────────────────────────────────────
    _day(15,
         ("Image carousel", "Prev/next, dots, autoplay that pauses on hover, looping and preloading.",
          "Index math for looping; timers and cleanup; pausing for focus and reduced motion; preloading neighbours."),
         ("Tree traversal", [(226, "Invert Binary Tree", "invert-binary-tree", "easy"), (104, "Maximum Depth of Binary Tree", "maximum-depth-of-binary-tree", "easy")],
          "Recursive base case; DFS vs BFS; recursion depth on skewed trees."),
         ("Chat app", "One-to-one and group chat over WebSockets.",
          "Connection lifecycle and reconnect; message ordering and dedupe; optimistic send with retry; read receipts; offline queue.")),
    _day(16,
         ("File explorer tree", "Expand/collapse folders; add, rename and delete files and folders.",
          "Recursive rendering; normalized vs nested state; immutable updates; keyboard navigation."),
         ("BFS on trees", [(100, "Same Tree", "same-tree", "easy"), (102, "Binary Tree Level Order Traversal", "binary-tree-level-order-traversal", "medium")],
          "Queue per level; knowing when a level ends; recursion vs iteration."),
         ("Streaming AI chat UI", "Chat with an LLM that streams tokens back — your Blackwave experience.",
          "SSE vs WebSocket; rendering partial output; cancel and retry; tool-progress states; recovering a dropped stream.")),
    _day(17,
         ("JS: EventEmitter & memoize", "on/off/once/emit; memoize with a cache key and an optional cache size.",
          "Listener storage; removing during emit; memory leaks; cache key choices and eviction."),
         ("Validating BSTs", [(98, "Validate Binary Search Tree", "validate-binary-search-tree", "medium")],
          "Passing min/max bounds down; why checking only children fails; in-order alternative."),
         ("Real-time dashboard", "Dashboard of charts that update live.",
          "Polling vs WebSocket vs SSE; batching updates; chart rendering cost; stale data indicators; partial failures per widget.")),
    _day(18,
         ("Kanban drag and drop", "Move cards within and between columns with HTML5 drag and drop.",
          "State shape for columns and order; drop position math; optimistic reorder; keyboard alternative."),
         ("BST properties", [(235, "Lowest Common Ancestor of a BST", "lowest-common-ancestor-of-a-binary-search-tree", "medium"),
                             (230, "Kth Smallest Element in a BST", "kth-smallest-element-in-a-bst", "medium")],
          "Using BST ordering to prune; iterative in-order with a stack; early stopping."),
         ("Kanban board", "Multi-user kanban board.",
          "Card and column components; ordering keys (fractional indexing); optimistic moves and conflicts; syncing other users' changes.")),
    _day(19,
         ("Tic-tac-toe N×N", "Configurable board size, winner detection, draw, and undo.",
          "Board state and derived winner; O(n) win check per move; history for undo; resetting."),
         ("Grid DFS/BFS", [(200, "Number of Islands", "number-of-islands", "medium")],
          "Marking visited in place vs a set; DFS vs BFS; stack depth on huge grids."),
         ("Email client", "Inbox, thread view, search and compose.",
          "List/detail layout; virtualized inbox; caching threads; drafts autosave; offline reading; send failures.")),
    _day(20,
         ("Virtualized list", "Render 10,000 rows smoothly with windowing.",
          "Visible range math; overscan; fixed vs variable row height; keeping scroll position."),
         ("Topological sort", [(207, "Course Schedule", "course-schedule", "medium")],
          "Graph from prerequisites; cycle detection via in-degree (Kahn) or DFS colours."),
         ("Photo feed", "Instagram-style feed and profile grid.",
          "Responsive images and formats; lazy loading and placeholders; prefetching; optimistic likes; upload flow.")),
    _day(21,
         ("Optimistic like + comments", "Like and comment instantly; roll back with a message when the request fails.",
          "Optimistic state vs server truth; rollback; duplicate submits; reconciling with refetch."),
         ("Review + trie", [(208, "Implement Trie (Prefix Tree)", "implement-trie-prefix-tree", "medium")],
          "Node structure; insert/search/startsWith; where tries power autocomplete. Then redo one missed problem from this week."),
         ("Review: chat app in 10 minutes", "Redo Day 15's design from scratch, timed, out loud.",
          "All five parts; this time lead with failure handling.")),

    # ── Week 4 · Interview mode ──────────────────────────────────────────────
    _day(22,
         ("JS: curry, compose, flatten", "curry(fn), compose/pipe, and flatten(array, depth).",
          "Arity and fn.length; left-to-right vs right-to-left; recursion vs iteration for flatten."),
         ("Intro DP", [(70, "Climbing Stairs", "climbing-stairs", "easy"), (198, "House Robber", "house-robber", "medium")],
          "State definition; recurrence; tabulation vs memoization; O(1) space."),
         ("Design system", "Shared component library used by several teams.",
          "Component API design; theming and tokens; accessibility by default; versioning and breaking changes; docs.")),
    _day(23,
         ("Progress bars with a concurrency limit", "Queue N bars, at most 3 filling at once.",
          "Queue state; starting the next on finish; cleanup on unmount; what changes for a real upload queue."),
         ("DP: unbounded choices", [(322, "Coin Change", "coin-change", "medium")],
          "dp[amount] definition; initialization with infinity; unreachable amounts."),
         ("Performance", "Make a slow page fast: Core Web Vitals and a loading strategy.",
          "Measuring first (LCP, INP, CLS); code splitting; image and font strategy; caching layers; avoiding re-renders.")),
    _day(24,
         ("Form wizard with draft", "Multi-step form, per-step validation, back/next, draft saved to localStorage.",
          "One form state vs per-step; restoring drafts safely; validation on navigation; final submit errors."),
         ("Intervals", [(56, "Merge Intervals", "merge-intervals", "medium")],
          "Sort by start; merge condition; touching intervals; where calendars use this."),
         ("State management", "Choose where each piece of state lives in a mid-size app.",
          "Local vs lifted vs global; server cache (TanStack Query) vs client state; URL state; costs of each.")),
    _day(25,
         ("Custom hooks", "useDebounce, usePrevious and useLocalStorage with tests you'd write.",
          "Effect cleanup; stale closures; SSR safety for localStorage; syncing across tabs."),
         ("Heaps", [(215, "Kth Largest Element in an Array", "kth-largest-element-in-an-array", "medium")],
          "Min-heap of size k vs quickselect; average vs worst case; when to use which."),
         ("Accessibility & i18n", "Make an existing app usable by everyone, in several languages.",
          "Semantic HTML first; focus management; screen-reader testing; string extraction; RTL and pluralization.")),
    _day(26,
         ("Streaming chat message list", "Auto-scroll to bottom unless the user scrolled up; 'new messages' pill; streaming text.",
          "Detecting user scroll intent; appending tokens without re-rendering everything; aria-live politeness."),
         ("Backtracking", [(78, "Subsets", "subsets", "medium")],
          "Choose / don't choose recursion; building and undoing the path; output size 2^n."),
         ("Frontend security", "Harden a frontend that renders user content and holds a session.",
          "XSS and escaping; CSP; CSRF; where tokens live (cookies vs storage); third-party scripts.")),
    _day(27,
         ("Month calendar with events", "Month grid, today highlight, events per day, overlapping events.",
          "Date math and time zones; building the 6×7 grid; overlap layout; keyboard navigation."),
         ("Backtracking with reuse", [(39, "Combination Sum", "combination-sum", "medium")],
          "Reusing candidates; pruning with a sorted array; avoiding duplicate combinations."),
         ("Offline & error monitoring", "Keep an app usable offline and know when it breaks in production.",
          "Service worker caching strategies; queued writes; conflict handling; error boundaries; logging and alerting.")),
    _day(28,
         ("Toast notification system", "Queue, auto-dismiss, pause on hover, stack limit, rendered in a portal.",
          "Global API design; timers per toast; accessibility (aria-live); cleanup on unmount."),
         ("Grid backtracking", [(79, "Word Search", "word-search", "medium")],
          "DFS with visited marking and restoring; pruning; time complexity."),
         ("Video watch page", "A YouTube-style watch page.",
          "Player and side-panel components; adaptive streaming; comments loading; recommendations; poor-network handling.")),

    # ── Mock interviews ──────────────────────────────────────────────────────
    _day(29,
         ("Mock: GitHub user search", "Unseen prompt, 45 minutes: search users, show results with pagination, handle errors. Narrate throughout; record yourself.",
          "Open with clarifying questions; plan out loud before typing; narrate trade-offs; leave 5 minutes to test and discuss improvements."),
         ("Mock: unseen pair", [(169, "Majority Element", "majority-element", "easy"), (53, "Maximum Subarray", "maximum-subarray", "medium")],
          "Treat it like the real thing: clarify, state the plan, code, test with examples, then complexity."),
         ("Mock: calendar app", "Unseen prompt, 13 minutes: design a Google Calendar-lite.",
          "Clarify scope first; then components, data flow, requests, performance and errors — in that order, out loud.")),
    _day(30,
         ("Mock: redo your weakest build", "Pick the build from weeks 1–3 that went worst; redo it in half the time, narrating.",
          "Compare with your first attempt: what you explained better, what still slows you down."),
         ("Mock: weakest pattern", [(128, "Longest Consecutive Sequence", "longest-consecutive-sequence", "medium")],
          "Set-based O(n) idea; only start counting at sequence starts. Then redo one problem from your weakest pattern."),
         ("Mock: weakest topic + cheat sheet", "Redo your weakest design, then write a one-page cheat sheet of the patterns you reuse.",
          "Which checklist part you now lead with, and which you still forget.")),
]

ITEM_KEYS: set[str] = {
    key
    for day in PLAN
    for key in (
        day["react"]["key"],
        day["system_design"]["key"],
        *(p["key"] for p in day["leetcode"]["problems"]),
    )
}
